### ISSUE TITLE
Selected state shows an extra background box

### ISSUE THREAD

**Issue by simoami** [aloco/SimpleButton#14]
I'm trying to enable a toggle feature through the `selected` property and using `UIControlState.Selected` for state. I get an extra blue layer in the background that I haven't been able to get rid off efficiently. Any tips?

<img width="281" alt="screen shot 2016-06-29 at 3 43 26 pm" src="https://cloud.githubusercontent.com/assets/2038264/16466215/491ac172-3e10-11e6-9b75-268bb02bc9c0.png">

**Comment by aloco** [comment]
Hi this blue layer is an effect of `UIButtonType.System` just use `UIButtonType.Custom` and it should be gone.

**Comment by simoami** [comment]
Thanks for clarifying.
