### ISSUE TITLE
Please update version on Cocoapods

### ISSUE THREAD

**Issue by nmccann** [aloco/SimpleButton#19]
Cocoapods still references the old 2.1.1 version, rather than the latest (v3 as of writing this).

It would be much appreciated if this could be updated. For now I'll just change my Podfile to point at the latest tag.

https://cocoapods.org/?q=simplebutton

P.S. Thank you for this excellent Pod :)

**Comment by aloco** [comment]
Hi, 

thank you for pointing out, should be updated. 

I don´t use cocoapods, so I would be happy if you can try again and let me know if it´s working. ✨

**Comment by nmccann** [comment]
Thank you @aloco - the new version works.
