### ISSUE TITLE
translatesAutoresizingMaskIntoConstraints = false break button's frame

### ISSUE THREAD

**Issue by Igor-Palaguta** [aloco/SimpleButton#9]
Hello,
In non autolayout view button's position is set to zero and size is minimized, removing this line of code fixes issue

Why do you have this? Can I break anything by removing it?

**Comment by aloco** [comment]
Hi, never tested this without Autolayout, thank you for pointing out this issue!

I don´t think this would break anything, would you mind to make the change and create a pull request?✌🏼

**Comment by Igor-Palaguta** [comment]
Yes sure, let me prepare this

**Comment by aloco** [comment]
thx https://github.com/aloco/SimpleButton/pull/10
